version: '3.3'

services:
  db:
    container_name: db
    image: mysql:5.7
    volumes:
     - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  ansible:
    container_name: ansible
    build:
      dockerfile: Dockerfile_ansible
      context: .
    restart: always
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "PathPrefix: /ansible"
  sonarqube:
    container_name: sonarqube
    build:
      dockerfile: Dockerfile_sonarqube
      context: .
    restart: always
    ports:
      - "9090:9090"
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "PathPrefix: /sonarqube"
      traefik.port: "9090"
   
  wordpress:
    depends_on:
     - db
    container_name: wordpress
    image: wordpress:latest
    ports:
     - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "PathPrefix: /wordpress"
      traefik.port: "8000"

  portainer:
    container_name: portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "PathPrefix: /portainer"
      traefik.port: "9000"

  gitlab:
    container_name: gitlab
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8929:8929'
      - '2224:22'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "PathPrefix: /gitlab"
      traefik.port: "8929"

  traefik:
    container_name: traefik
    image: traefik:v2.0
    command: --api.insecure=true --providers.docker
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "PathPrefix: /traefik"
      traefik.port: "8080"


volumes:
    db_data: {}
    portainer_data:
