# traefik.toml
################################################################
# Global configuration
################################################################

# defaultEntryPoints = ["http", "https"]
defaultEntryPoints = ["http"]

logLevel = "ERROR"

[accessLog]
  format = "common"

[entryPoints]
  [entryPoints.http]
  address = ":80"

[web]
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "compose.local"
watch = true
exposedbydefault = false

